# This has to be >= v1.57.0 for module plugin system support.
version: v1.64.6
name: custom-gcl
destination: ./bin
plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: latest # Or a fixed version for reproducible builds.
