version: "3.8"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ads_db
    ports:
      - "5432:5432"