name: Lint source code
on:
  push:
    branches:
      - main
      - origin
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Build custom golangci-lint plugin
        run: |
          $(which golangci-lint) custom


      - name: Update dependencies and tidy up
        run: |
          go mod tidy
      - name: Run custom linter
        run: |
          ./bin/custom-gcl run ./... --timeout=10m
